# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50d365a86e690eb9dce14e1a427002e42d9ff04974e86502e7eb4837763f5f2033adf3f16095a7d0c3c32aae9403a69782ecde4826589da564f860a0892e2339

test:
  secret_key_base: 31e77d79525d8907b487d616c6e3b4af28839ab0d6f4a2c8fd02fa522e9675b30d97cf6d2644e3a79910be443909fa4bc5f06943936b972773d6d835d43896fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

telegram:
  bot:
    token: 202727802:AAEbcpEYOp5YmtZ47mm8mCKGY2nzI_XN9u0
    username: GaragemcaBot
